export default {
  path:'/movie',
  redirect:'/movie/nowplay',
  component:()=>import('@/views/movie'),
  children:[{
    path:'city',
    component:()=>import('@/components/city'),
  },
  {
    path:'comesoon',
    component:()=>import('@/components/comesoon'),
  },
  {
    path:'search',
    component:()=>import('@/components/search'),
  },
  {
    path:'nowplay',
    component:()=>import('@/components/nowplay'),
  },
  {
    path:'detail/n/:movieid',
    components:{
    default:()=>import('@/components/nowplay'),
    detail:()=>import('@/views/movie/detail'),},
    props:{
      detail:true
    }
  },
  {
    path:'detail/s/:movieid',
    components:{
    default:()=>import('@/components/comesoon'),
    detail:()=>import('@/views/movie/detail'),},
    props:{
      detail:true
    }
  },
  
]
}